# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 410d0bd74dd5e49560a27882fa7d9357478ccfa2667d2c0d5533d823204ed2e7aa21c4f7a477e4eb1efcacec7011e799144ce781669e37ede8e55aa82ff70232

test:
  secret_key_base: 2ece6e8cc71873918da74c842124136b4041395044bf56d5f24b5c61b9d4ef3fb01961d38a9d29e61276a28d1fba160496348a576673d24ce974b64618a47b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
